server:
  port: 9981
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum-f2?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
# jpa
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect